import type { FeatureFlag } from './types'

export const seedFlags: FeatureFlag[] = [
  {
    id: 'flag-smart-replies',
    key: 'ai_smart_replies',
    name: 'AI Smart Replies',
    description: 'Suggests concise responses based on conversation context.',
    type: 'release',
    enabled: true,
    updatedAt: '2024-06-24T10:20:00.000Z',
    updatedBy: 'Olivia Rhye',
  },
  {
    id: 'flag-summary',
    key: 'ai_conversation_summary',
    name: 'Conversation Summary',
    description: 'Generates a short summary when a support conversation closes.',
    type: 'release',
    enabled: true,
    updatedAt: '2024-06-21T16:42:00.000Z',
    updatedBy: 'Marcus Chen',
  },
  {
    id: 'flag-tone',
    key: 'ai_tone_rewrite',
    name: 'Tone Rewrite',
    description: 'Lets users adjust the tone of generated copy before sending.',
    type: 'experiment',
    enabled: false,
    updatedAt: '2024-06-18T09:10:00.000Z',
    updatedBy: 'Sofia Davis',
  },
  {
    id: 'flag-docs',
    key: 'ai_docs_search',
    name: 'AI Docs Search',
    description: 'Answers questions using indexed internal documentation.',
    type: 'release',
    enabled: true,
    updatedAt: '2024-06-16T14:18:00.000Z',
    updatedBy: 'Olivia Rhye',
  },
  {
    id: 'flag-auto-tagging',
    key: 'ai_auto_tagging',
    name: 'Automatic Tagging',
    description: 'Classifies incoming requests with suggested issue tags.',
    type: 'experiment',
    enabled: false,
    updatedAt: '2024-06-12T11:05:00.000Z',
    updatedBy: 'Marcus Chen',
  },
  {
    id: 'flag-voice',
    key: 'ai_voice_transcription',
    name: 'Voice Transcription',
    description: 'Transcribes voice notes into editable text.',
    type: 'experiment',
    enabled: false,
    updatedAt: '2024-06-07T08:30:00.000Z',
    updatedBy: 'Sofia Davis',
  },
]
